### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkmgit** [jnduli/blog_jnduli.co.ke#12]
Is there a license for the contents of https://jnduli.co.ke and https://comics.jnduli.co.ke/

**Comment by bkmgit** [comment]
As an example for an image see https://www.gnu.org/graphics/dog.html

**Comment by BonfaceKilz** [comment]
Benson Muite ***@***.***> aliandika:

> As an example for an image see https://www.gnu.org/graphics/dog.html

Cute 🤣🤣🤣🤣

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by jnduli** [comment]
Thanks for catching this, I hadn't thought about it....it should be a creative commons licence. I'll update the repo with one once I've got the exact one and close the ticket.

**Comment by BonfaceKilz** [comment]
John Nduli Kilyungi ***@***.***>
aliandika:

> Thanks for catching this, I hadn't thought about it....it should be a creative commons licence. I'll update the repo with one once I've got the exact one and close the ticket.
>

Use this list to help you out in figuring out what
to use:

    <https://www.gnu.org/licenses/license-list.html#OtherLicenses>

I've seen alot of people use "CC-BY-SA" - what
version you use may depend on you.

-- 
(To agree without understanding is inane.
   To disagree without understanding is impudent.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by jnduli** [comment]
License is http://creativecommons.org/licenses/by/4.0/.

I've set it up here in the blog repo: https://github.com/jnduli/blog_jnduli/blob/80f31c03a12f0d4af21b1141e61ed560c09cc93d/LICENSE#L1

Here are screenshots for the comic and blog live servers:
![image](https://user-images.githubusercontent.com/19635979/198858050-87b9547f-e544-46c9-a3c8-a0d0139e7368.png)

![image](https://user-images.githubusercontent.com/19635979/198858056-161e6b3e-b732-4975-9c86-774d70bc9863.png)

Closing the issue.
